### ISSUE TITLE
Why is there one repo for one language?

### ISSUE THREAD

**Issue by yihong0618** [spencercjh/sync-leetcode-today-problem-cpp-example#1]
~

**Comment by spencercjh** [comment]
emm. It 's easy~

**Comment by yihong0618** [comment]
> emm. It 's easy~

Ha, I also face the problem before, I choose env~ 
Something like this.


![image](https://user-images.githubusercontent.com/15976103/102459377-781ba000-4080-11eb-8a2c-5269de450374.png)
![image](https://user-images.githubusercontent.com/15976103/102459391-7eaa1780-4080-11eb-8bf8-9fe720cd25e5.png)
